# $FreeBSD$

PORTNAME=	edict
PORTVERSION=	1.17
CATEGORIES=	japanese xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Lisp Interface to EDICT, Kanji Dictionary

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
