# $FreeBSD$

PORTNAME=	semantic
PORTVERSION=	1.21
CATEGORIES=	lang xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Semantic bovinator (Yacc/Lex for XEmacs) includes Senator

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
