# $FreeBSD$

PORTNAME=	calc
PORTVERSION=	1.26
CATEGORIES=	math xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs calculator

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
