# $FreeBSD$

PORTNAME=	forms
PORTVERSION=	1.15
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Forms editing support (obsolete, use Widget instead)

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
