# $FreeBSD$

PORTNAME=	jde
PORTVERSION=	1.52
CATEGORIES=	java xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Integrated Development Environment for Java

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
