# $FreeBSD$

PORTNAME=	frame-icon
PORTVERSION=	1.11
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Set up mode-specific icons for each frame under XEmacs

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
