# $FreeBSD$

PORTNAME=	dictionary
PORTVERSION=	1.16
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Interface to RFC2229 dictionary servers

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
