# $FreeBSD$

PORTNAME=	cogre
PORTVERSION=	1.02
CATEGORIES=	graphics xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Graph editing mode

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
