# $FreeBSD$

PORTNAME=	xemacs-base
PORTVERSION=	2.27
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Fundamental XEmacs support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
