# $FreeBSD$

PORTNAME=	edit-utils
PORTVERSION=	2.43
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Miscellaneous editor extensions

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
