# $FreeBSD$

PORTNAME=	hm--html-menus
PORTVERSION=	1.24
CATEGORIES=	www xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	HTML editing

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
