# $FreeBSD$

PORTNAME=	w3m
PORTVERSION=	1.10
CATEGORIES=	www xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	An Emacs interface to w3m

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
