# $FreeBSD$

PORTNAME=	leim
PORTVERSION=	1.31
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Quail. All non-English and non-Japanese language support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
