# $FreeBSD$

PORTNAME=	sieve
PORTVERSION=	1.18
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Manage Sieve email filtering scripts

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
