# $FreeBSD$

PORTNAME=	vc-cc
PORTVERSION=	1.22
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Version Control for ClearCase (UnFree) systems

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
