# $FreeBSD$

PORTNAME=	apel
PORTVERSION=	1.37
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	A Portable Emacs Library used by XEmacs MIME support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
