# $FreeBSD$

PORTNAME=	mmm-mode
PORTVERSION=	1.05
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Multiple major modes in a single buffer

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
