# $FreeBSD$

PORTNAME=	escreen
PORTVERSION=	1.01
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Multiple editing sessions within a single frame (like screen)

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
