# $FreeBSD$

PORTNAME=	prom-wl
PORTVERSION=	1.10
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Procmail reader for Wanderlust on Emacsen

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
