# $FreeBSD$

PORTNAME=	zenirc
PORTVERSION=	1.16
CATEGORIES=	irc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	ZENIRC IRC Client

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
