# $FreeBSD$

PORTNAME=	erc
PORTVERSION=	0.23
CATEGORIES=	irc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	ERC is an Emacs InternetRelayChat client

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
