# $FreeBSD$

PORTNAME=	latin1
PORTVERSION=	1.0
CATEGORIES=	editors xepkgs

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Meta port for latin1 XEmacs pacakges

LICENSE=	GPLv2

RUN_DEPENDS=	xepkg-c-support${PKGNAMESUFFIX}>=1.22:${PORTSDIR}/lang/xepkg-c-support \
		xepkg-cc-mode${PKGNAMESUFFIX}>=1.45:${PORTSDIR}/lang/xepkg-cc-mode \
		xepkg-debug${PKGNAMESUFFIX}>=1.18:${PORTSDIR}/devel/xepkg-debug \
		xepkg-dired${PKGNAMESUFFIX}>=1.20:${PORTSDIR}/sysutils/xepkg-dired \
		xepkg-edit-utils${PKGNAMESUFFIX}>=2.43:${PORTSDIR}/editors/xepkg-edit-utils \
		xepkg-efs${PKGNAMESUFFIX}>=1.34:${PORTSDIR}/net/xepkg-efs \
		xepkg-fsf-compat${PKGNAMESUFFIX}>=1.19:${PORTSDIR}/editors/xepkg-fsf-compat \
		xepkg-mail-lib${PKGNAMESUFFIX}>=1.80:${PORTSDIR}/mail/xepkg-mail-lib \
		xepkg-net-utils${PKGNAMESUFFIX}>=1.56:${PORTSDIR}/net/xepkg-net-utils \
		xepkg-os-utils${PKGNAMESUFFIX}>=1.41:${PORTSDIR}/sysutils/xepkg-os-utils \
		xepkg-prog-modes${PKGNAMESUFFIX}>=2.20:${PORTSDIR}/lang/xepkg-prog-modes \
		xepkg-text-modes${PKGNAMESUFFIX}>=1.98:${PORTSDIR}/textproc/xepkg-text-modes \
		xepkg-time${PKGNAMESUFFIX}>=1.14:${PORTSDIR}/misc/xepkg-time \
		xepkg-xemacs-base${PKGNAMESUFFIX}>=2.27:${PORTSDIR}/editors/xepkg-xemacs-base \
		xepkg-xemacs-devel${PKGNAMESUFFIX}>=1.80:${PORTSDIR}/devel/xepkg-xemacs-devel

USES=		xemacs

.include <bsd.port.mk>
