# $FreeBSD$

PORTNAME=	pc
PORTVERSION=	1.28
CATEGORIES=	emulators xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	PC style interface emulation

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
