# $FreeBSD$

PORTNAME=	xetla
PORTVERSION=	1.02
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	(S)XEmacs Frontend to GNU/arch (tla)

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
