# $FreeBSD$

PORTNAME=	oo-browser
PORTVERSION=	1.05
CATEGORIES=	www xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	The Multi-Language Object-Oriented Code Browser

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
