# $FreeBSD$

PORTNAME=	net-utils
PORTVERSION=	1.56
CATEGORIES=	net xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Miscellaneous Networking Utilities

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
