# $FreeBSD$

PORTNAME=	sgml
PORTVERSION=	1.11
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	SGML/Linuxdoc-SGML editing

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
