# $FreeBSD$

PORTNAME=	xlib
PORTVERSION=	1.14
CATEGORIES=	x11 xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs interface to X server

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
