# $FreeBSD$

PORTNAME=	sh-script
PORTVERSION=	1.24
CATEGORIES=	lang xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Support for editing shell scripts

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
