# $FreeBSD$

PORTNAME=	sdoc-mode
PORTVERSION=	1.10
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	SmartDoc mode

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
