# $FreeBSD$

PORTNAME=	cookie
PORTVERSION=	1.15
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Spook and Yow (Zippy quotes)

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
