# $FreeBSD$

PORTNAME=	riece
PORTVERSION=	1.23
CATEGORIES=	irc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	IRC (Internet Relay Chat) client for Emacs

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
