# $FreeBSD$

PORTNAME=	view-process
PORTVERSION=	1.13
CATEGORIES=	www xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	A Unix process browsing tool

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
