# $FreeBSD$

PORTNAME=	ecrypto
PORTVERSION=	0.21
CATEGORIES=	security xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Crypto functionality in Emacs Lisp

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
