# Created by: Kazuhiko Kiriyama <kiri@TrueFC.org>
# $FreeBSD:$

PORTNAME=	opentools
PORTVERSION=	1.3
CATEGORIES=	sysutils

MAINTAINER=	kiri@truefc.org
COMMENT=	Gadget tools for BSD Unix desktop

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	TrueFC

NO_ARCH=	yes
NO_BUILD=	yes

OPENTOOLSBINS=	autocol.rb bwsr.sh create-portstree.sh emcs.sh \
		latex2latex.rb mailprc.sh newest.sh sbackup.sh sct.sh \
		sdoc2page.rb sdoc2sdoc.rb slgn.sh w3.sh wl.sh xtrm.sh

.include <bsd.port.mk>
