# $FreeBSD$

PORTNAME=	efs
PORTVERSION=	1.34
CATEGORIES=	net xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Treat files on remote systems the same as local files

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
