# $FreeBSD$

PORTNAME=	git
PORTVERSION=	1.10
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	A user interface for git

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
