# $FreeBSD$

PORTNAME=	sounds-au
PORTVERSION=	1.12
CATEGORIES=	audio xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	XEmacs Sun sound files

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
