# $FreeBSD$

PORTNAME=	xslt-process
PORTVERSION=	1.12
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	XSLT processing support

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
