# $FreeBSD$

PORTNAME=	psgml-dtds
PORTVERSION=	1.03
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Deprecated collection of DTDs for psgml

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
