# $FreeBSD$

PORTNAME=	mercurial
PORTVERSION=	1.10
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Support for the Mercurial distributed SCM

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
