# $FreeBSD$

PORTNAME=	easypg
PORTVERSION=	1.03
CATEGORIES=	security xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	GnuPG interface for Emacs

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
