# $FreeBSD$

PORTNAME=	os-utils
PORTVERSION=	1.41
CATEGORIES=	sysutils xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Miscellaneous Operating System utilities

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
