# $FreeBSD$

PORTNAME=	ocaml
PORTVERSION=	0.06
CATEGORIES=	lang xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Objective Caml editing support

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
