# $FreeBSD$

PORTNAME=	guided-tour
PORTVERSION=	0.52
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Phil Sung's Guided Tour of Emacs

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
