# $FreeBSD$

PORTNAME=	mailcrypt
PORTVERSION=	2.14
CATEGORIES=	security xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Support for messaging encryption with PGP

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
