# $FreeBSD$

PORTNAME=	misc-games
PORTVERSION=	1.22
CATEGORIES=	games xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Other amusements and diversions

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
