# $FreeBSD$

PORTNAME=	elib
PORTVERSION=	1.13
CATEGORIES=	lang xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Portable Emacs Lisp utilities library

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
