# $FreeBSD$

PORTNAME=	ddskk
PORTVERSION=	1.10
CATEGORIES=	japanese xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Daredevil SKK (Simple Kana to Kanji conversion program)

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
