# $FreeBSD$

PORTNAME=	footnote
PORTVERSION=	1.16
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Footnoting in mail message editing modes

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
