# $FreeBSD$

PORTNAME=	speedbar
PORTVERSION=	1.29
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Provides a separate frame with convenient references

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
