# $FreeBSD$

PORTNAME=	gnats
PORTVERSION=	1.17
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	XEmacs bug reports

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
