# $FreeBSD$

PORTNAME=	time
PORTVERSION=	1.14
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Display time and date on the modeline

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
