# $FreeBSD$

PORTNAME=	skk
PORTVERSION=	1.24
CATEGORIES=	japanese xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Japanese Language Input Method

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

ENCODING_FILES=	lisp/skk/*.el etc/skk/ReadMe etc/skk/SKK-JISYO.* etc/skk/SKK.tut*

.include <bsd.port.mk>
