# $FreeBSD$

PORTNAME=	eudc
PORTVERSION=	1.40
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs Unified Directory Client (LDAP, PH)

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
