# $FreeBSD$

PORTNAME=	reftex
PORTVERSION=	1.34
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs support for LaTeX cross-references, citations..

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
