# $FreeBSD$

PORTNAME=	viper
PORTVERSION=	1.67
CATEGORIES=	emulators xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	VI emulation support

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
