# $FreeBSD$

PORTNAME=	x-symbol
PORTVERSION=	1.11
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Semi WYSIWYG for LaTeX, HTML, etc, using additional fonts

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
