# $FreeBSD$

PORTNAME=	sounds-wav
PORTVERSION=	1.12
CATEGORIES=	audio xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	XEmacs Microsoft sound files

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
