# $FreeBSD$

PORTNAME=	egg-its
PORTVERSION=	1.27
CATEGORIES=	japanese xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Wnn (4.2 and 6) support. SJ3 support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
