# $FreeBSD$

PORTNAME=	ecb
PORTVERSION=	1.22
CATEGORIES=	www xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs source code browser

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
