# $FreeBSD$

PORTNAME=	mail-lib
PORTVERSION=	1.80
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Fundamental lisp files for providing email support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
