# $FreeBSD$

PORTNAME=	latin-unity
PORTVERSION=	1.20
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Find single ISO 8859 character set to encode a buffer

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
