# $FreeBSD$

PORTNAME=	gnus
PORTVERSION=	1.94
CATEGORIES=	news xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	The Gnus Newsreader and Mailreader

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
