# $FreeBSD$

PORTNAME=	xslide
PORTVERSION=	1.09
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	XSL editing support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
