# $FreeBSD$

PORTNAME=	mule-ucs
PORTVERSION=	1.18
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Extended coding systems(including Unicode) for XEmacs

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
