# $FreeBSD$

PORTNAME=	crisp
PORTVERSION=	1.15
CATEGORIES=	emulators xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Crisp/Brief emulation

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
