# $FreeBSD$

PORTNAME=	mine
PORTVERSION=	1.16
CATEGORIES=	games xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Minehunt Game

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
