# $FreeBSD$

PORTNAME=	idlwave
PORTVERSION=	1.32
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Editing and Shell mode for the Interactive Data Language

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
