# $FreeBSD$

PORTNAME=	eterm
PORTVERSION=	1.18
CATEGORIES=	emulators xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Terminal emulation

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
