# $FreeBSD$

PORTNAME=	xwem
PORTVERSION=	1.23
CATEGORIES=	x11-wm xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	X Emacs Window Manager

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
