# $FreeBSD$

PORTNAME=	ibuffer
PORTVERSION=	1.10
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Advanced replacement for buffer-menu

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
