# $FreeBSD$

PORTNAME=	texinfo
PORTVERSION=	1.30
CATEGORIES=	textproc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	XEmacs TeXinfo support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
