# $FreeBSD$

PORTNAME=	latin-euro-standards
PORTVERSION=	1.09
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Support for the Latin{7,8,9,10} character sets and coding systems

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
