# $FreeBSD$

PORTNAME=	tm
PORTVERSION=	1.39
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs MIME support not needed for gnus >= 5.8.0

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
