# $FreeBSD$

PORTNAME=	dired
PORTVERSION=	1.20
CATEGORIES=	sysutils xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Manage file systems

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
