# Created by: xeamcs@FreeBSD.org
# $FreeBSD$

PORTNAME=	xemacs-canna
CATEGORIES=	japanese editors

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	The stable version of the XEmacs with CANNA input method

CONFLICTS?=	emacs-[0-9]* emacs-devel-[0-9]* \
		xemacs-devel-[0-9]* ja-xemacs-devel-* \
		xemacs-common-[0-9]*  xemacs-devel-common-[0-9]*

XEMACS_INSTALL=	${PORTNAME}
DESCR=		${.CURDIR}/pkg-descr
PKGMESSAGE=	${.CURDIR}/pkg-message

L10N=		ja

MASTERDIR=	${.CURDIR}/../../editors/xemacs

.include "${MASTERDIR}/Makefile"
