# $FreeBSD$

PORTNAME=	edt
PORTVERSION=	1.14
CATEGORIES=	emulators xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	DEC EDIT/EDT emulation

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
