# $FreeBSD$

PORTNAME=	ispell
PORTVERSION=	1.32
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Spell-checking with GNU ispell

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
