# $FreeBSD$

PORTNAME=	ps-print
PORTVERSION=	1.12
CATEGORIES=	print xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Printing functions and utilities

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
