# $FreeBSD$

PORTNAME=	bbdb
PORTVERSION=	1.32
CATEGORIES=	database xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	The Big Brother Data Base

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
