# $FreeBSD$

PORTNAME=	build
PORTVERSION=	1.15
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Build XEmacs from within UNIX or Windows

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
