# $FreeBSD$

PORTNAME=	rmail
PORTVERSION=	1.14
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	An obsolete Emacs mailer

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
