# $FreeBSD$

PORTNAME=	cc-mode
PORTVERSION=	1.45
CATEGORIES=	lang xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	C,C++,Objective-C,Java,CORBA IDL,Pike and AWK language support

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
