# $FreeBSD$

PORTNAME=	sasl
PORTVERSION=	1.16
CATEGORIES=	security xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Simple Authentication and Security Layer (SASL) library

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
