# $FreeBSD$

PORTNAME=	clearcase
PORTVERSION=	1.10
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	New Clearcase Version Control for XEmacs (UNIX, Windows)

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
