# $FreeBSD$

PORTNAME=	w3
PORTVERSION=	1.35
CATEGORIES=	www xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	A Web browser

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
