# $FreeBSD$

PORTNAME=	debug
PORTVERSION=	1.18
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	GUD, gdb, dbx debugging support

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
