# $FreeBSD$

PORTNAME=	pgg
PORTVERSION=	1.07
CATEGORIES=	security xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Emacs interface to various PGP implementations

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
