# $FreeBSD$

PORTNAME=	tramp
PORTVERSION=	1.40
CATEGORIES=	net xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Remote shell-based file editing

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
