# $FreeBSD$

PORTNAME=	strokes
PORTVERSION=	1.10
CATEGORIES=	misc xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Mouse enhancement utility

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
