# $FreeBSD$

PORTNAME=	prog-modes
PORTVERSION=	2.20
CATEGORIES=	lang xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Support for various programming languages

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
