# $FreeBSD$

PORTNAME=	fsf-compat
PORTVERSION=	1.19
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	FSF Emacs compatibility files

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
