# $FreeBSD$

PORTNAME=	eshell
PORTVERSION=	1.18
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Command shell implemented entirely in Emacs Lisp

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
