# $FreeBSD$

PORTNAME=	supercite
PORTVERSION=	1.21
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	An Emacs citation tool for News and Mail messages

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
