# $FreeBSD$

PORTNAME=	eieio
PORTVERSION=	1.07
CATEGORIES=	editors xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Enhanced Implementation of Emacs Interpreted Objects

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
