# $FreeBSD$

PORTNAME=	mule
PORTVERSION=	1.0
CATEGORIES=	editors xepkgs

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Meta port for Mule XEmacs pacakges

LICENSE=	GPLv2

RUN_DEPENDS=	xepkg-ddskk${PKGNAMESUFFIX}>=1.10:${PORTSDIR}/japanese/xepkg-ddskk \
		xepkg-edict${PKGNAMESUFFIX}>=1.17:${PORTSDIR}/japanese/xepkg-edict \
		xepkg-egg-its${PKGNAMESUFFIX}>=1.27:${PORTSDIR}/japanese/xepkg-egg-its \
		xepkg-latin-euro-standards${PKGNAMESUFFIX}>=1.09:${PORTSDIR}/editors/xepkg-latin-euro-standards \
		xepkg-latin-unity${PKGNAMESUFFIX}>=1.20:${PORTSDIR}/editors/xepkg-latin-unity \
		xepkg-leim${PKGNAMESUFFIX}>=1.31:${PORTSDIR}/editors/xepkg-leim \
		xepkg-locale${PKGNAMESUFFIX}>=1.28:${PORTSDIR}/editors/xepkg-locale \
		xepkg-lookup${PKGNAMESUFFIX}>=1.15:${PORTSDIR}/misc/xepkg-lookup \
		xepkg-mule-base${PKGNAMESUFFIX}>=1.56:${PORTSDIR}/editors/xepkg-mule-base \
		xepkg-mule-ucs${PKGNAMESUFFIX}>=1.18:${PORTSDIR}/editors/xepkg-mule-ucs

USES=		xemacs

.include <bsd.port.mk>
