# $FreeBSD$

PORTNAME=	games
PORTVERSION=	1.20
CATEGORIES=	games xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Tetris, Sokoban, and Snake

LICENSE=	GPLv2

USE_XEPKGS=	yes
NO_ARCH=	yes

.include <bsd.port.mk>
