# $FreeBSD$

PORTNAME=	mh-e
PORTVERSION=	1.32
CATEGORIES=	mail xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	The XEmacs Interface to the MH Mail System

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
