#
MASTERDIR=	${.CURDIR}/../u-boot-master

U_BOOT_SLAVE_PORTREVISION_2020.10=	1
#MASTERDIR=	${.CURDIR}/../u-boot-2020.07

MODEL=		pinebook-pro
BOARD_CONFIG=	pinebook-pro-rk3399_defconfig
FAMILY=		rk3399

EXTRA_PATCHES=	${.CURDIR}/files/

.include "${MASTERDIR}/Makefile"

