# $FreeBSD$

PORTNAME=	vc
PORTVERSION=	1.48
CATEGORIES=	devel xepkgs
MASTER_SITES=	XEP

MAINTAINER=	xemacs@FreeBSD.org
COMMENT=	Version Control for Free systems

LICENSE=	GPLv2

USES=		xemacs
NO_ARCH=	yes

.include <bsd.port.mk>
